## Importing Data
Let's cover some basic and common data import operations in Pandas.  To prepare, let's download three files in three data formats: CSV, SQLite, and JSON.

In [3]:
import pandas as pd
import numpy as np
import urllib.request
from pathlib import Path

In [4]:


# Define the raw data directory
raw_data_dir = Path("../data/raw")

# Create the directory if it doesn't exist
raw_data_dir.mkdir(parents=True, exist_ok=True)

# Download CSV
urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/thomasnield/machine-learning-demo-data/master/classification/maintenance_predict.csv?raw=true",
    raw_data_dir / "maintenance.csv"
)

# Download SQLite database
urllib.request.urlretrieve(
    "https://github.com/thomasnield/anaconda_intro_to_sql/blob/main/company_operations.db?raw=true",
    raw_data_dir / "company_operations.db"
)

# Download JSON
urllib.request.urlretrieve(
    "https://gist.githubusercontent.com/thomasnield/7daae45b907263808d1374235e73a27d/raw/32763976868928518a7e6b65211704390359601a/json_tabuler.json",
    raw_data_dir / "customers.json"
)

print("Downloads successful")

Downloads successful

To help view the raw contents of a text file, let's implement this `read_text()` function

In [5]:
def read_text(filepath):
    with open(filepath) as f:
        return f.readlines()

Let's take a look at the CSV file `maintenance.csv` first and view its raw contents line by line

In [6]:
read_text(raw_data_dir/'maintenance.csv')

['DAYS_SINCE_INSTALL,FLIGHT_HOURS,ENV_TEMPERATURE,REPLACEMENT_NEEDED\n',
 '93,792,126,1\n',
 '11,107,113,1\n',
 '23,152,110,1\n',
 '32,375,110,1\n',
 '141,701,110,1\n',
 '21,143,107,1\n',
 '68,453,107,1\n',
 '72,754,107,1\n',
 '33,185,106,1\n',
 '106,715,106,1\n',
 '152,1046,106,1\n',
 '83,1113,106,1\n',
 '175,1616,106,1\n',
 '198,1823,106,1\n',
 '183,1832,106,1\n',
 '11,60,105,1\n',
 '15,67,105,1\n',
 '127,250,105,1\n',
 '129,750,105,1\n',
 '33,285,103,0\n',
 '73,677,103,1\n',
 '142,1825,102,0\n',
 '1,6,102,0\n',
 '62,239,101,0\n',
 '40,167,100,0\n',
 '32,301,100,0\n',
 '92,988,100,1\n',
 '135,1002,99,0\n',
 '61,334,99,0\n',
 '134,473,98,1\n',
 '80,729,98,1\n',
 '127,441,97,0\n',
 '20,204,96,0\n',
 '29,213,96,0\n',
 '156,1228,96,1\n',
 '3,24,95,0\n',
 '80,859,95,1\n',
 '192,943,94,0\n',
 '128,322,93,0\n',
 '56,656,93,0\n',
 '152,1475,93,0\n',
 '26,239,93,0\n',
 '95,379,92,0\n',
 '116,1000,92,0\n',
 '89,373,92,0\n',
 '134,585,92,1\n',
 '13,144,91,0\n',
 '61,269,91,0\n',
 '74,301,91,0\n',
 '45,429,91,0\n',
 '200,1237,91,0\n',
 '177,1255,91,0\n',
 '165,1403,91,0\n',
 '95,900,91,1\n',
 '154,1608,91,1\n',
 '63,434,90,0\n',
 '125,1478,90,0\n',
 '117,1244,89,1\n',
 '69,544,89,0\n',
 '18,91,88,0\n',
 '164,1046,88,1\n',
 '167,1533,88,1\n',
 '125,544,88,0\n',
 '92,730,88,1\n',
 '133,772,88,0\n',
 '197,344,87,0\n',
 '45,371,87,0\n',
 '35,283,87,1\n',
 '135,1230,87,1\n',
 '53,628,87,0\n',
 '82,486,86,0\n',
 '12,118,86,0\n',
 '90,768,86,0\n',
 '16,126,85,0\n',
 '12,181,85,0\n',
 '195,1586,85,1\n',
 '183,2241,85,1\n',
 '98,612,85,0\n',
 '171,1417,84,1\n',
 '145,1620,84,1\n',
 '122,818,84,0\n',
 '79,995,84,0\n',
 '82,156,83,0\n',
 '200,1114,83,1\n',
 '174,1187,83,1\n',
 '167,2397,83,1\n',
 '39,301,83,1\n',
 '40,304,83,0\n',
 '36,307,83,0\n',
 '45,423,83,0\n',
 '51,531,83,0\n',
 '108,607,83,1\n',
 '124,896,83,0\n',
 '161,1042,82,1\n',
 '169,1482,82,1\n',
 '178,1534,82,1\n',
 '78,628,82,1\n',
 '101,723,82,1\n',
 '98,1155,81,0\n',
 '131,1246,81,1\n',
 '164,1801,81,1\n',
 '149,2110,81,1\n',
 '31,115,81,0\n',
 '21,223,81,0\n',
 '3,4,80,0\n',
 '23,149,80,0\n',
 '63,424,80,0\n',
 '189,1116,80,1\n',
 '128,146,80,0\n',
 '51,457,80,0\n',
 '175,1053,79,1\n',
 '61,462,79,1\n',
 '108,722,79,0\n',
 '111,902,79,0\n',
 '66,402,78,0\n',
 '10,61,78,0\n',
 '34,346,78,0\n',
 '137,621,78,0\n',
 '93,656,78,0\n',
 '194,775,78,0\n',
 '61,822,78,0\n',
 '170,1717,77,1\n',
 '43,459,77,0\n',
 '173,619,77,1\n',
 '79,937,77,0\n',
 '15,84,76,0\n',
 '43,268,76,0\n',
 '38,424,76,0\n',
 '159,1265,76,1\n',
 '169,1681,76,1\n',
 '50,525,76,0\n',
 '110,561,76,0\n',
 '139,1316,75,1\n',
 '3,15,75,0\n',
 '95,556,75,0\n',
 '83,606,75,0\n',
 '179,1244,74,1\n',
 '131,1317,74,1\n',
 '1,5,74,0\n',
 '66,627,74,1\n',
 '161,853,74,0\n',
 '97,910,74,0\n',
 '200,1337,73,0\n',
 '58,325,73,1\n',
 '155,1336,73,1\n',
 '140,1446,73,1\n',
 '179,1863,73,1\n',
 '39,331,73,0\n',
 '119,379,73,0\n',
 '118,386,73,0\n',
 '48,258,72,0\n',
 '63,429,72,0\n',
 '149,494,72,0\n',
 '199,1113,72,1\n',
 '70,506,72,0\n',
 '97,608,72,0\n',
 '14,133,71,0\n',
 '179,1088,71,1\n',
 '145,1151,71,1\n',
 '138,1232,71,1\n',
 '186,1254,71,1\n',
 '183,1910,71,1\n',
 '193,2051,71,1\n',
 '17,123,71,0\n',
 '20,196,71,1\n',
 '25,226,71,0\n',
 '57,652,71,0\n',
 '175,1201,70,0\n',
 '85,288,70,1\n',
 '90,1105,70,1\n',
 '166,1560,70,1\n',
 '143,1740,70,1\n',
 '17,165,70,0\n',
 '20,246,70,0\n',
 '148,537,70,1\n',
 '59,562,70,0\n',
 '51,393,69,0\n',
 '150,1600,69,1\n',
 '192,2179,69,1\n',
 '48,363,69,0\n',
 '165,872,69,1\n',
 '119,983,69,0\n',
 '126,984,69,0\n',
 '38,268,68,0\n',
 '109,363,68,0\n',
 '150,1080,68,1\n',
 '67,714,68,0\n',
 '148,997,68,0\n',
 '9,99,67,0\n',
 '40,449,67,0\n',
 '194,1648,67,1\n',
 '16,139,67,0\n',
 '44,349,67,0\n',
 '44,379,67,0\n',
 '48,392,67,0\n',
 '102,504,67,0\n',
 '102,618,67,1\n',
 '117,818,67,0\n',
 '148,971,67,0\n',
 '36,346,66,0\n',
 '101,441,66,0\n',
 '37,480,66,1\n',
 '117,1162,66,1\n',
 '118,1212,66,1\n',
 '13,73,66,0\n',
 '24,163,66,0\n',
 '135,474,66,0\n',
 '64,625,66,0\n',
 '183,648,66,0\n',
 '98,923,66,0\n',
 '86,950,66,0\n',
 '3,36,65,0\n',
 '134,1276,65,1\n',
 '17,132,65,0\n',
 '99,557,65,0\n',
 '88,686,65,0\n',
 '67,752,65,0\n',
 '101,921,65,0\n',
 '68,320,64,1\n',
 '136,1236,64,1\n',
 '181,1563,64,1\n',
 '186,1786,64,1\n',
 '10,114,64,0\n',
 '78,553,64,0\n',
 '79,725,64,0\n',
 '22,190,63,1\n',
 '136,1169,63,1\n',
 '84,824,63,0\n',
 '95,1066,62,1\n',
 '191,1220,62,1\n',
 '156,1925,62,1\n',
 '79,487,62,0\n',
 '112,641,62,0\n',
 '92,774,62,1\n',
 '111,889,62,0\n',
 '2,16,61,0\n',
 '177,66,61,0\n',
 '37,239,61,0\n',
 '67,427,61,0\n',
 '65,499,61,0\n',
 '169,1307,61,1\n',
 '22,121,61,0\n',
 '23,175,61,0\n',
 '29,252,61,0\n',
 '35,283,61,0\n',
 '46,415,61,0\n',
 '141,490,61,0\n',
 '161,507,61,0\n',
 '120,843,61,1\n',
 '2,13,60,0\n',
 '51,331,60,0\n',
 '165,1261,60,0\n',
 '106,1057,60,1\n',
 '193,1127,60,1\n',
 '134,1199,60,1\n',
 '160,1246,60,1\n',
 '188,2044,60,1\n',
 '19,167,60,0\n',
 '132,707,60,0\n',
 '62,763,60,0\n',
 '62,418,59,0\n',
 '8,27,59,0\n',
 '10,64,59,0\n',
 '49,569,59,0\n',
 '53,599,59,0\n',
 '157,705,59,0\n',
 '62,740,59,0\n',
 '13,165,58,0\n',
 '16,86,58,1\n',
 '29,423,58,1\n',
 '195,1110,58,1\n',
 '134,1111,58,1\n',
 '86,1303,58,1\n',
 '39,243,58,0\n',
 '127,515,58,0\n',
 '159,515,58,0\n',
 '61,607,58,0\n',
 '106,922,58,0\n',
 '93,939,58,0\n',
 '15,160,57,0\n',
 '110,1432,57,1\n',
 '174,1456,57,1\n',
 '132,1474,57,1\n',
 '3,30,57,0\n',
 '17,127,57,0\n',
 '43,203,57,0\n',
 '132,501,57,0\n',
 '108,591,57,0\n',
 '112,607,57,0\n',
 '80,659,57,0\n',
 '104,743,57,0\n',
 '98,952,57,0\n',
 '2,8,56,0\n',
 '38,223,56,0\n',
 '90,1053,56,1\n',
 '125,1059,56,1\n',
 '128,1096,56,1\n',
 '145,1376,56,1\n',
 '186,1951,56,1\n',
 '8,43,56,0\n',
 '18,101,56,0\n',
 '30,117,56,0\n',
 '68,317,56,0\n',
 '58,529,56,0\n',
 '88,538,56,1\n',
 '134,792,56,0\n',
 '6,50,55,0\n',
 '53,333,55,1\n',
 '175,1147,55,1\n',
 '145,2037,55,1\n',
 '176,2058,55,1\n',
 '18,148,55,0\n',
 '65,294,55,0\n',
 '35,387,55,0\n',
 '102,589,55,0\n',
 '73,665,55,0\n',
 '60,676,55,0\n',
 '100,710,55,0\n',
 '41,205,54,0\n',
 '133,1040,54,1\n',
 '87,1126,54,1\n',
 '197,798,54,1\n',
 '194,1719,53,0\n',
 '53,185,53,1\n',
 '195,1156,53,1\n',
 '153,1263,53,1\n',
 '130,1287,53,1\n',
 '178,1648,53,1\n',
 '30,120,53,0\n',
 '53,633,53,0\n',
 '59,635,53,0\n',
 '174,1244,52,1\n',
 '149,1265,52,1\n',
 '122,514,52,0\n',
 '78,549,52,0\n',
 '77,626,52,0\n',
 '75,841,52,0\n',
 '99,846,52,0\n',
 '187,1770,51,1\n',
 '22,104,51,0\n',
 '1,3,51,0\n',
 '10,37,51,0\n',
 '13,116,51,0\n',
 '94,173,51,0\n',
 '95,547,51,0\n',
 '64,657,51,1\n',
 '76,791,51,0\n',
 '170,1258,50,1\n',
 '188,1382,50,1\n',
 '200,1448,50,1\n',
 '112,943,50,0\n',
 '16,134,49,0\n',
 '99,1323,49,0\n',
 '196,1228,49,1\n',
 '153,1435,49,1\n',
 '35,461,49,0\n',
 '96,604,49,0\n',
 '84,635,49,0\n',
 '125,1382,48,1\n',
 '82,505,48,0\n',
 '1,9,47,0\n',
 '137,1158,47,1\n',
 '150,1360,47,1\n',
 '151,1437,47,1\n',
 '191,2008,47,1\n',
 '36,97,47,1\n',
 '67,683,47,0\n',
 '133,892,47,1\n',
 '66,920,47,0\n',
 '104,1041,46,1\n',
 '146,1324,46,1\n',
 '180,1403,46,1\n',
 '198,1424,46,1\n',
 '34,466,46,1\n',
 '21,103,45,0\n',
 '142,2094,45,0\n',
 '125,1210,45,1\n',
 '12,113,45,0\n',
 '20,114,45,0\n',
 '43,391,45,0\n',
 '163,903,45,1\n',
 '144,1658,44,1\n',
 '61,501,44,0\n',
 '111,891,44,0\n',
 '29,291,43,0\n',
 '183,361,43,0\n',
 '92,651,43,0\n',
 '2,13,42,0\n',
 '8,79,42,0\n',
 '108,1139,42,1\n',
 '169,1203,42,1\n',
 '17,155,42,0\n',
 '18,157,42,0\n',
 '81,513,42,0\n',
 '119,904,42,0\n',
 '109,696,41,0\n',
 '35,273,40,0\n',
 '172,1218,40,1\n',
 '16,82,40,0\n',
 '52,718,40,0\n',
 '97,1362,39,1\n',
 '115,1437,39,1\n',
 '30,185,38,1\n',
 '8,78,38,0\n',
 '34,403,37,1\n',
 '151,1220,37,1\n',
 '130,120,36,0\n',
 '124,1064,36,1\n',
 '162,508,36,0\n',
 '121,579,36,0\n',
 '148,780,36,0\n',
 '150,888,36,0\n',
 '98,918,36,0\n',
 '28,182,35,0\n',
 '137,1137,35,0\n',
 '157,1329,35,1\n',
 '156,254,35,0\n',
 '73,468,34,1\n',
 '129,1536,34,1\n',
 '71,575,34,0\n',
 '163,1194,33,1\n',
 '89,507,33,0\n',
 '44,229,32,1\n',
 '42,415,31,0\n',
 '94,739,31,0\n',
 '186,973,31,0\n',
 '155,1142,30,1\n',
 '122,955,30,0\n',
 '181,1084,29,0\n',
 '142,1033,29,1\n',
 '69,618,29,0\n',
 '33,281,28,0\n',
 '199,1317,27,1\n',
 '18,136,26,0\n',
 '91,1017,26,1\n',
 '122,1664,26,1\n',
 '1,3,25,0\n',
 '95,593,24,1\n',
 '54,364,23,0\n',
 '57,448,22,0\n',
 '155,650,21,0\n',
 '176,1697,17,1\n',
 '33,188,12,0\n',
 '32,474,7,0\n']

We can load it into Pandas DataFrame by using the `read_csv()` function and pass it the location and/or name of the file

In [7]:
pd.read_csv(raw_data_dir/'maintenance.csv')

     DAYS_SINCE_INSTALL  FLIGHT_HOURS  ENV_TEMPERATURE  REPLACEMENT_NEEDED
0                    93           792              126                   1
1                    11           107              113                   1
2                    23           152              110                   1
3                    32           375              110                   1
4                   141           701              110                   1
..                  ...           ...              ...                 ...
439                  57           448               22                   0
440                 155           650               21                   0
441                 176          1697               17                   1
442                  33           188               12                   0
443                  32           474                7                   0

[444 rows x 4 columns]

## Reading a SQL Database
Next let's look at a SQL database.  There are many SQL database platforms like My SQL, Oracle, MS SQL Server, and PostgreSQL.  They all use relational tables to store data, and we can use the `read_sql()` function in Pandas to easily execute a SQL query against a database connection.

In our example, we will use SQLite since it is lightweight and easily stores data in a simple database file with we just downloaded.  SQLite support is also included in Python's standard library.  Here is how we connect to a SQLite database and run a query against the `CUSTOMER` table using Pandas `read_sql()` function.

In [8]:
import sqlite3

conn = sqlite3.connect(raw_data_dir/'company_operations.db')

pd.read_sql("SELECT * FROM CUSTOMER", conn)

,CUSTOMER_ID,CUSTOMER_NAME,ADDRESS,CITY,STATE,ZIP,CATEGORY
0,1,Alpha Medical,18745 Train Dr,Dallas,TX,75021,INDUSTRIAL
1,2,Oak Cliff Base,2379 Cliff Ave,Abbevile,LA,70510,GOVERNMENT
2,3,Sports Unlimited,1605 Station Dr,Alexandrai,LA,71301,COMMERCIAL
3,4,Riley Sporting Goods,9854 Firefly Blvd,Austin,TX,78701,COMMERCIAL
4,5,Lite Industrial,462 Roadrunner Blvd,Houston,TX,77254,INDUSTRIAL
5,6,Prairie Sports Center,689 Stadium Way,Tulsa,OK,74101,COMMERCIAL
6,7,Facility 95,2396 Runway Dr,Oklahoma City,OK,73101,GOVERNMENT
7,8,Allen Stadium,573 HIllcrest Rd,Allen,TX,75002,COMMERCIAL
8,9,Dent Research,392 45th St,Waco,TX,76700,INDUSTRIAL
9,10,Gamma Solutions,2752 27th St,Phoenix,AZ,85001,COMMERCIAL

## Reading a JSON File
Last let's look at how to read data from a JSON file.  Let's look at the contests of `customers.json`

In [9]:
read_text(raw_data_dir/'customers.json')

['[\n',
 '     {\n',
 '            "ID" : 1,\n',
 '            "NAME": "Alpha Medical",\n',
 '            "ADDRESS" : "18745 Train Dr",\n',
 '            "CITY" : "Dallas",\n',
 '            "STATE": "TX",\n',
 '            "ZIP" : 75021,\n',
 '            "CATEGORY" : "INDUSTRIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 2,\n',
 '            "NAME": "Oak Cliff Base",\n',
 '            "ADDRESS" : "2379 Cliff Ave",\n',
 '            "CITY" : "Abbevile",\n',
 '            "STATE": "LA",\n',
 '            "ZIP" : 70510,\n',
 '            "CATEGORY": "GOVERNMENT"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 3,\n',
 '            "NAME": "Sports Unlimited",\n',
 '            "ADDRESS" : "1605 Station Dr",\n',
 '            "CITY" : "Alexandrai",\n',
 '            "STATE": "LA",\n',
 '            "ZIP" : 71301,\n',
 '            "CATEGORY" : "COMMERCIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 4,\n',
 '            "NAME": "Riley Sporting Goods",\n',
 '            "ADDRESS" : "9854 Firefly Blvd",\n',
 '            "CITY" : "Austin",\n',
 '            "STATE": "TX",\n',
 '            "ZIP" : 78701,\n',
 '            "CATEGORY" : "COMMERCIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 5,\n',
 '            "NAME": "Lite Industrial",\n',
 '            "ADDRESS" : "462 Roadrunner Blvd",\n',
 '             "CITY" : "Houston",\n',
 '            "STATE": "TX",\n',
 '            "ZIP" : 77254,\n',
 '            "CATEGORY" : "INDUSTRIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 6,\n',
 '            "NAME": "Prairie Sports Center",\n',
 '            "ADDRESS" : "689 Stadium Way",\n',
 '            "CITY" : "Tulsa",\n',
 '            "STATE": "OK",\n',
 '            "ZIP" : 74101,\n',
 '            "CATEGORY" : "COMMERCIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 7,\n',
 '            "NAME": "Facility 95",\n',
 '            "ADDRESS" : "2396 Runway Dr",\n',
 '            "CITY" : "Oklahoma City",\n',
 '            "STATE": "OK",\n',
 '            "ZIP" : 73101,\n',
 '            "CATEGORY" : "GOVERNMENT"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 8,\n',
 '            "NAME": "Allen Stadium",\n',
 '            "ADDRESS" : "573 HIllcrest Rd",\n',
 '            "CITY" : "Allen",\n',
 '            "STATE": "TX",\n',
 '            "ZIP" : 75002,\n',
 '            "CATEGORY" : "COMMERCIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 9,\n',
 '            "NAME": "Dent Research",\n',
 '            "ADDRESS" : "392 45th St",\n',
 '            "CITY" : "Waco",\n',
 '            "STATE": "TX",\n',
 '            "ZIP" : 76700,\n',
 '            "CATEGORY" : "INDUSTRIAL"\n',
 '        },\n',
 '        {\n',
 '            "ID" : 10,\n',
 '            "NAME": "Gamma Solutions",\n',
 '            "ADDRESS" : "2752 27th St",\n',
 '            "CITY" : "Phoenix",\n',
 '            "STATE": "AZ",\n',
 '            "ZIP" : 85001,\n',
 '            "CATEGORY" : "COMMERCIAL"\n',
 '        }\n',
 '    ]\n']

Assuming the JSON is structured in a way that can be mapped into a tabular structure easily, we can use Pandas `read_json() function to read a JSON file into a DataFrame easily.

In [11]:
pd.read_json(raw_data_dir/'customers.json')

,ID,NAME,ADDRESS,CITY,STATE,ZIP,CATEGORY
0,1,Alpha Medical,18745 Train Dr,Dallas,TX,75021,INDUSTRIAL
1,2,Oak Cliff Base,2379 Cliff Ave,Abbevile,LA,70510,GOVERNMENT
2,3,Sports Unlimited,1605 Station Dr,Alexandrai,LA,71301,COMMERCIAL
3,4,Riley Sporting Goods,9854 Firefly Blvd,Austin,TX,78701,COMMERCIAL
4,5,Lite Industrial,462 Roadrunner Blvd,Houston,TX,77254,INDUSTRIAL
5,6,Prairie Sports Center,689 Stadium Way,Tulsa,OK,74101,COMMERCIAL
6,7,Facility 95,2396 Runway Dr,Oklahoma City,OK,73101,GOVERNMENT
7,8,Allen Stadium,573 HIllcrest Rd,Allen,TX,75002,COMMERCIAL
8,9,Dent Research,392 45th St,Waco,TX,76700,INDUSTRIAL
9,10,Gamma Solutions,2752 27th St,Phoenix,AZ,85001,COMMERCIAL